services:
  webserver:
    image: nginx:alpine
    container_name: filitour_nginx
    # (sin puertos publicados: el trafico entra por NPM)
    volumes:
      - ./:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./docker/nginx/waf-rules.conf:/etc/nginx/conf.d/waf-rules.conf
    depends_on:
      - app
    networks:
      - filitour_network
    restart: unless-stopped

  app:
    image: php:8.2-fpm-alpine
    container_name: filitour_php
    volumes:
      - ./:/var/www/html
    # CORRECCIÓN AQUÍ: Forzamos a PHP-FPM a escuchar en 0.0.0.0:9000
    command: >
      sh -c "
        sed -i 's/listen = 127.0.0.1:9000/listen = 0.0.0.0:9000/' /usr/local/etc/php-fpm.d/www.conf &&
        docker-php-ext-install pdo pdo_mysql &&
        php-fpm
      "
    depends_on:
      - db
    networks:
      - filitour_network
    restart: unless-stopped

  db:
    image: mariadb:10.6
    container_name: filitour_mysql
    environment:
      MYSQL_ROOT_PASSWORD: Root#Fili2026#Kq9Zx4Vb
      MYSQL_DATABASE: filitour_db
    ports:
      - "127.0.0.1:3307:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - filitour_network
    restart: unless-stopped

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: filitour_pma
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: Root#Fili2026#Kq9Zx4Vb
    ports:
      - "127.0.0.1:8081:80"
    depends_on:
      - db
    networks:
      - filitour_network
    restart: unless-stopped

networks:
  filitour_network:
    driver: bridge

volumes:
  db_data:
